version: '3'
services:
  api:
    container_name: thinkific-api
    image: "thinkific-api"
    build: .
    links:
      - mongo:mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:example@mongo:27017/
      SPRING_DATA_MONGODB_DATABASE: sportsmanagement-dev
      SPRING_PROFILES_ACTIVE: dev
    env_file:
      - ./secrets.env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
